name:
    ncpca

channels:
    - pytorch
    - nvidia
    - conda-forge

dependencies:
    - python=3.9
    - pip
    - black
    - pytest
    - numpy
    - scipy
    - pandas
    - matplotlib
    - seaborn
    - pytorch-cuda=11.7
    - pytorch=1.13.1
    - torchvision>=0.12
    - scikit-learn
    - tqdm
    - ipykernel
    - ipywidgets>=7.0,<8.0
    - jupyter
     
    - pip:
        - pydove
